---

name: Generate CLI Dist

"on":
  release:
    types: [published]
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-24.04
    container: fedora:42
    permissions:
      # needed for uploading release artifact
      contents: write
    steps:
      - name: Install basic dependencies
        run: |
          dnf install -y git gh upx

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add workspace as git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install rust toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Prerequisites
        run: |
          dnf install -y just lsb_release
          just ci=true prerequisites

      - name: Setup
        run: just ci=true setup-release

      - name: Build CLI
        run: meson compile cli-cargo-build -C _mesonbuild

      - name: Optimize Binary
        run: |
          strip _mesonbuild/rnote-cli
          upx --best --lzma _mesonbuild/rnote-cli

      - name: Register archive file names
        id: register_archive_file_names
        run: |
          cp _mesonbuild/rnote-cli _mesonbuild/rnote-cli-linux-x86_64
          cd _mesonbuild && sha256sum rnote-cli-linux-x86_64 > rnote-cli-linux-x86_64.sha256sum
          echo "artifact=rnote-cli-linux-x86_64" >> $GITHUB_OUTPUT
          echo "sha=rnote-cli-linux-x86_64.sha256sum" >> $GITHUB_OUTPUT

      - name: Upload CLI archive (workflow artifact)
        uses: actions/upload-artifact@v4
        with:
          name: rnote-cli-linux-artifact
          path: |
            _mesonbuild/${{ steps.register_archive_file_names.outputs.artifact }}
            _mesonbuild/${{ steps.register_archive_file_names.outputs.sha }}
          include-hidden-files: true
          if-no-files-found: error

      - name: Upload CLI archive (release asset)
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            _mesonbuild/${{ steps.register_archive_file_names.outputs.artifact }} --repo ${{ github.repository }}
          gh release upload ${{ github.ref_name }} \
            _mesonbuild/${{ steps.register_archive_file_names.outputs.sha }} --repo ${{ github.repository }}
