---

name: Release Windows CLI

"on":
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    permissions:
      # needed for uploading release artifact
      contents: write
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Set installer name
        id: set_installer_name
        shell: bash
        run: |
          echo "name=rnote-cli-windows-x86_64.exe" >> $GITHUB_OUTPUT

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          install: |
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-upx
            unzip
            git
            mingw-w64-x86_64-xz
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-diffutils
            mingw-w64-x86_64-desktop-file-utils
            mingw-w64-x86_64-appstream

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-gnu

      - name: Configure PATH
        run: echo "export PATH=$PATH:/c/Users/$USER/.cargo/bin" > ~/.bashrc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prerequisites
        run: |
          cargo install --locked just
          just ci=true prerequisites-win

      - name: Setup
        run: just ci=true setup-win-installer '${{ steps.set_installer_name.outputs.name }}'

      - name: Build
        run: meson compile cli-cargo-build -C _mesonbuild

      - name: Optimize Binary
        run: |
          strip _mesonbuild/rnote-cli.exe
          upx --best --lzma _mesonbuild/rnote-cli.exe

      - name: Prepare Artifact
        shell: bash
        id: prepare_artifact
        run: |
          cp _mesonbuild/rnote-cli.exe _mesonbuild/${{ steps.set_installer_name.outputs.name }}
          cd _mesonbuild && sha256sum ${{ steps.set_installer_name.outputs.name }} > ${{ steps.set_installer_name.outputs.name }}.sha256sum

      - name: Upload CLI (workflow artifact)
        uses: actions/upload-artifact@v4
        with:
          name: rnote-cli-windows-artifact
          path: |
            _mesonbuild/${{ steps.set_installer_name.outputs.name }}
            _mesonbuild/${{ steps.set_installer_name.outputs.name }}.sha256sum
          if-no-files-found: error

      - name: Upload CLI (release asset)
        if: ${{ github.event_name == 'release' }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} _mesonbuild/${{ steps.set_installer_name.outputs.name }} --repo ${{ github.repository }}
          gh release upload ${{ github.ref_name }} _mesonbuild/${{ steps.set_installer_name.outputs.name }}.sha256sum --repo ${{ github.repository }}
